import type { Metadata } from 'next';
import './globals.css';
import { ThemeModeScript } from 'flowbite-react';
import Link from 'next/link';
import { Navbar, NavbarBrand, NavbarCollapse, NavbarLink, NavbarToggle } from 'flowbite-react';
import Image from 'next/image';
import { Roboto } from 'next/font/google';
import { gql } from '@apollo/client';
import client from './services/graphQlClient';
import { getCategories } from './services/categories';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();
  console.log(categories);

  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${roboto.className} antialiased`}>
        <Navbar fluid rounded>
          <NavbarBrand as={Link} href="/">
            <Image
              src="/images/doitsu-technology-logo.svg"
              width={60}
              height={60}
              className="mr-3"
              alt="Doitsu Technology"
            />
            <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
              D Tech
            </span>
          </NavbarBrand>
          <NavbarToggle />
          <NavbarCollapse>
            <NavbarLink href="#" active>
              Home
            </NavbarLink>
            <NavbarLink as={Link} href="#">
              About
            </NavbarLink>
            <NavbarLink href="#">Services</NavbarLink>
            <NavbarLink href="#">Pricing</NavbarLink>
            <NavbarLink href="#">Contact</NavbarLink>
          </NavbarCollapse>
        </Navbar>

        {children}
      </body>
    </html>
  );
}
