import type { Metadata } from 'next';
import './globals.css';
import { ThemeModeScript } from 'flowbite-react';
import Link from 'next/link';
import { Navbar, NavbarBrand, NavbarCollapse, NavbarToggle } from 'flowbite-react';
import Image from 'next/image';
import { Roboto } from 'next/font/google';
import { getCategories } from './services/categories';
import MyNavbarLink from './components/my-navbar-link';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${roboto.className} antialiased`}>
        <Navbar fluid rounded>
          <NavbarBrand as={Link} href="/">
            <Image
              src="/images/doitsu-technology-logo.png"
              width={60}
              height={60}
              className="mr-3"
              alt="Doitsu Technology"
            />
            <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
              D Tech
            </span>
          </NavbarBrand>
          <NavbarToggle />
          <NavbarCollapse>
            <MyNavbarLink slug="/" displayName="Home"></MyNavbarLink>
            {categories.map((category) => (
              <MyNavbarLink
                slug={`/blogs/${category.slug}`}
                displayName={category.displayName}
                key={category.id}
              ></MyNavbarLink>
            ))}
          </NavbarCollapse>
        </Navbar>

        {children}
      </body>
    </html>
  );
}
