query getCategories {
  categories(filters: { categoryType: { eq: BLOG }, parentId: {is_null: "true"} }) {
    nodes {
      id
      parentId
      displayName
      selfRefReverse {
        nodes {
          id,
          parentId,
          displayName
        }
      }
    }
  }
}
